CREATE DATABASE IF NOT EXISTS AGE7;

CREATE TABLE IF NOT EXISTS AGE7.DM_UNIDADE_ORC
 (ID_UNIDADE_ORC INT,
  SQA_UNIDADE_ORCAM BIGINT,
  ANO_EXERCICIO SMALLINT,
  CD_UNIDADE_ORC INT,
  ID_GRUPO_ADMINISTRACAO TINYINT,
  GRUPO_ADMINISTRACAO VARCHAR(100),
  ID_ADMINISTRACAO TINYINT,
  ADMINISTRACAO VARCHAR(100),
  NOME VARCHAR(100),
  SIGLA VARCHAR(30)
 );

CREATE TABLE IF NOT EXISTS AGE7.FT_RECEITA_V2018
 (ID_TEMPO SMALLINT,
  ID_UNIDADE_ORC INT,
  ID_ORIGEM INT,
  ID_ESPECIE INT,
  ID_DESDOBRAMENTO_1 INT,
  ID_DESDOBRAMENTO_2 INT,
  ID_DESDOBRAMENTO_3 INT,
  ID_TIPO INT,
  ID_ITEM INT,
  ID_SUBITEM INT,
  ID_FONTE INT,
  CD_FONTE TINYINT,
  CD_CLASSIFICACAO_REC BIGINT,
  ANO_PARTICAO SMALLINT,
  VR_EFETIVADO DECIMAL(15,2)
 );
